//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingShare.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUser
    {
        public mUser()
        {
            this.tProjectMember = new HashSet<tProjectMember>();
        }
    
        public int UserId { get; set; }
        public string LoginId { get; set; }
        public string PasswordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nickname { get; set; }
        public string Email { get; set; }
        public bool isConfirm { get; set; }
        public bool isLock { get; set; }
        public int LockCount { get; set; }
        public System.DateTime LockTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual ICollection<tProjectMember> tProjectMember { get; set; }
    }
}
