//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingShare.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketEntities : DbContext
    {
        public TicketEntities()
            : base("name=TicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mMenu> mMenu { get; set; }
        public virtual DbSet<mUser> mUser { get; set; }
        public virtual DbSet<mUserType> mUserType { get; set; }
        public virtual DbSet<tProject> tProject { get; set; }
        public virtual DbSet<tProjectMember> tProjectMember { get; set; }
        public virtual DbSet<tTicket> tTicket { get; set; }
    }
}
